# .github/workflows/scraper.yml
name: Scraping IPHAN Notícias

on:
  schedule:
    - cron: '*/30 * * * *'        # roda de 30 em 30 min
  workflow_dispatch:

permissions:
  contents: write                 # preciso para dar push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout completo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # precisamos do histórico p/ forçar push

      # 2. Node → 20
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. dependências
      - name: Instalar dependências
        run: npm install --no-audit --no-fund

      # 4. Executa o scraper
      - name: Rodar script de scraping
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"   # ignora TLS do site IPHAN
        run: node scripts/scraper-iphan.js

      # 5. Commita e P U S H A — sem pull
      - name: Commit e enviar alterações, se existirem
        uses: EndBug/add-and-commit@v9
        with:
          add:              'noticias_iphan.json'
          default_author:   github_actions
          message:          'chore: atualizar noticias_iphan.json'
          pull:             false                    #  << DESLIGA o pull
          push:             '--force-with-lease'     #  << só força se remoto não mudou
