name: Scraping IPHAN Notícias

on:
  schedule:          # roda automático → de 30 em 30 min
    - cron: '*/30 * * * *'
  workflow_dispatch: # botão “Run workflow”

permissions:
  contents: write    # autoriza commit

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona repositório completo (para poder dar push)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Prepara Node 20
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Instala dependências declaradas no package.json
      - name: Instalar dependências
        run: npm install --no-audit --no-fund

      # 4) Executa o scraper  
      #    (TLS 0 evita erro de certificado do gov.br)
      - name: Rodar script de scraping
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
        run: node scripts/scrape-all.js

      # 5) Faz commit *só se* `noticias.json` mudou
      - name: Commit e push (se houver alterações)
        uses: EndBug/add-and-commit@v9
        with:
          add: 'noticias.json'
          default_author: github_actions
          message: 'chore: atualizar noticias.json'
          pull: '--rebase --autostash'   # evita conflitos

