# .github/workflows/scraper.yml (ou scraper-iphan.yml)

name: Scraping IPHAN Notícias
on:
  schedule:
    - cron:  "*/30 * * * *"      # a cada 30 min
  workflow_dispatch:

permissions:
  contents: write                # necessário p/ push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    # 1) checkout **com fetch-depth 0** para ter o histórico completo
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2) Node
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    # 3) dependências
    - name: Instalar dependências
      run: npm install --no-audit --no-fund

    # 4) run scraper (TLS off só p/ IPHAN)
    - name: Rodar script de scraping
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
      run: node scripts/scraper-iphan.js

    # 5) commit + push (faz pull --rebase antes)
    - name: Commit e enviar alterações, se existirem
      uses: EndBug/add-and-commit@v9
      with:
        add:      'noticias_iphan.json'
        default_author: github_actions
        message:  'chore: atualizar noticias_iphan.json'
        pull:     '--rebase'          # <-- evita non-fast-forward
        # se preferir forçar:
        # push: '--force'
