name: Scraping IPHAN Notícias

on:
  schedule:
    - cron:  '*/30 * * * *'      # a cada 30 min
  workflow_dispatch:

permissions:
  contents: write                # necessário para fazer push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) clona o repositório (fetch-depth 0 → permite push)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # mantém o GITHUB_TOKEN configurado

      # 2) prepara o Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) instala dependências declaradas no package.json
      - name: Instalar dependências
        run: npm install --no-audit --no-fund

      # 4) executa o scraper (desliga validação TLS p/ certificados gov.br)
      - name: Rodar script de scraping
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"   # aceita cert. cadeia incompleta
        run: node scripts/scraper-iphan.js

      # 5) commita e envia SE o arquivo mudou
      - name: Commit e push (se houver alterações)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: atualizar noticias_iphan.json'
          file_pattern:   'noticias_iphan.json'
          commit_user_name:  github-actions
          commit_user_email: github-actions[bot]@users.noreply.github.com
          push_options: '--force-with-lease'
