name: Scraping IPHAN Notícias

on:
  schedule:                       # roda a cada 30 min
    - cron:  '*/30 * * * *'
  workflow_dispatch:              # permite rodar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona o repositório
      - uses: actions/checkout@v4

      # 2. Prepara o Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Instala dependências declaradas no package.json
      - run: npm ci

      # 4. EXECUTA o scraper
      #    --> aqui desligamos a verificação TLS *apenas* para este processo
      - name: Rodar script de scraping
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"   # <-- **SOLUÇÃO 1**
        run: node scripts/scraper-iphan.js

      # 5. Se o JSON mudou, faz commit e push
      - name: Commit e enviar alterações, se existirem
        uses: EndBug/add-and-commit@v9
        with:
          add: 'noticias_iphan.json'
          default_author: github_actions
          message: 'chore: atualizar noticias_iphan.json'
