# .github/workflows/scraper.yml
name: Scraping IPHAN Notícias

on:
  schedule:
    - cron: '*/30 * * * *'     # a cada 30 min
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1) clone completo (para poder rebazar/forçar push)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) dependências
      - name: Instalar dependências
        run: npm install --no-audit --no-fund

      # 4) roda o scraper
      - name: Rodar script de scraping
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"   # ignora TLS (certificado IPHAN)
        run: node scripts/scraper-iphan.js

      # 5) commit + pull --rebase --autostash + push --force-with-lease
      - name: Commit e enviar alterações, se existirem
        uses: EndBug/add-and-commit@v9
        with:
          add:              'noticias_iphan.json'
          default_author:   github_actions
          message:          'chore: atualizar noticias_iphan.json'
          pull:             '--rebase --autostash'   # <-- aqui!
          push:             '--force-with-lease'     # só força se o remoto não mudou

